### ISSUE TITLE
multi node multi gpu

### ISSUE THREAD

**Issue by JiahaoYao** [yang-song/score_inverse_problems#1]
Hi @yang-song , thanks for sharing the code. I wonder whether the code supports multi node multi gpu  training. I see the code include `jax.device` and `jax.local_device`. But I wonder how connection among the gpus is set up? Thanks again!

**Comment by yang-song** [comment]
it supports multi gpu single node training. It should work for multi node training with TPUs. I'm not sure JAX supports multi node GPU training now, but maybe it does

**Comment by JiahaoYao** [comment]
thanks @yang-song !
