### ISSUE TITLE
Module is not compatible

### ISSUE THREAD

**Issue by adahfbch** [yang-song/score_inverse_problems#7]
Hi, I have tried to install the modules according to requirements file, but the commit ID corresponding to flax is invalid. So I installed the latest version of flax directly，but this version is not compatible with the versions of other required packages. I tried to downgrade the version of flax, but it still didn't work. Could you tell me the exact version of Flax? Thanks!
And maybe there will be a pytorch version?

**Comment by computerAItest** [comment]
> Hi, I have tried to install the modules according to requirements file, but the commit ID corresponding to flax is invalid. So I installed the latest version of flax directly，but this version is not compatible with the versions of other required packages. I tried to downgrade the version of flax, but it still didn't work. Could you tell me the exact version of Flax? Thanks! And maybe there will be a pytorch version?

Did you solve it, I have the same problem
